name: Rebuild EV Charging Monitor

on:
  schedule:
    - cron: "0 3 * * *"   # Runs daily at 3:00 AM UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run EV Charging Monitor script
        env:
          OCM_API_KEY: ${{ secrets.OCM_API_KEY }}
        run: |
          python build_ev_atlas.py

      - name: Commit updated map
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add outputs/index.html
          git commit -m "Automated rebuild: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push
